spring:
  profiles:
    active: dev
mybatis:
  typeAliasesPackage: com.zcc.springboot.spring4test1.entity
  mapperLocations: classpath:mapper/*.xml
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/zcc
    username: root
    password: 123456a
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0
